######
image: docker:git

variables:
  IMAGE: inspira-crawlers  
  GCR_IMAGE: gcr.io/inspira-development/inspira-crawlers

services:
  - docker:dind

build:
  stage: build
  before_script:
    - echo $GOOGLE_CLOUD_ACCOUNT
    - echo $GOOGLE_CLOUD_ACCOUNT | docker login -u _json_key --password-stdin https://gcr.io
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build -t "$IMAGE${tag}" .
    - docker tag "$IMAGE${tag}" $GCR_IMAGE:$CI_COMMIT_BRANCH
    - docker push $GCR_IMAGE:$CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
