version: '3'

volumes:
  redis-data: { }

services:
  chrome:
    image: selenium/node-chrome:4.6.0-20221104
    shm_size: 1gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.6.0-20221104
    shm_size: 1gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.6.0-20221104
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  celery: &celery
    image: inspira-crawlers
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: 'inspira-crawlers-celery'
    command: 'celery -A tasks worker -Q persistence,crawlers,crawlers.tjrj,crawlers.trf3,crawlers.tjmg,crawlers.trf4,crawlers.scrfb,crawlers.stj,crawlers.tst,crawlers.titsp,crawlers.carf,crawlers.tjsp,crawlers.tjrs,crawlers.tjba,downloader --concurrency=2 -E --loglevel=INFO'
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/opt/service
      - ./service-account.json:/etc/gcloud/service-account.json

  #  beat:
  #    <<: *celery
  #    container_name: 'inspira-crawlers-beat'
  #    command: 'celery -A tasks beat -s .celerybeat-schedule'
  #    volumes:
  #      - .:/opt/service
  #      - .celerybeat-schedule:/opt/service/.celerybeat-schedule

  celery_tjsp:
    <<: *celery
    container_name: 'inspira-crawlers-tjsp'
    command: 'celery -A tasks worker -Q tjsp --concurrency=2 -E --loglevel=INFO -n worker.tjsp'

  celery_tjsp_pdf:
    <<: *celery
    container_name: 'inspira-crawlers-tjsp-pdf'
    command: 'celery -A tasks worker -Q tjsp.pdf --concurrency=5 -E --loglevel=INFO -n worker.tjsp-pdf'

  redis:
    image: redis:6.2.5
    container_name: "redis"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    logging:
      driver: none

  flower:
    image: inspira-crawlers
    container_name: 'inspira-crawlers-flower'
    command: 'celery -A tasks flower'
    ports:
      - "5555:5555"
    environment:
      - CELERYD_HIJACK_ROOT_LOGGER=false
      - C_FORCE_ROOT='true'
    volumes:
      - .:/opt/service
