---
version: '2'
services:
  redis:
    image: redis:latest
    container_name: 'inspira-crawlers-redis'
    ports:
      - "5555:5555"

  celery: &celery
    build: .
    image: inspira-crawlers
    network_mode: 'service:redis'
    container_name: 'inspira-crawlers-celery'
    command: 'celery -A tasks worker -Q persistence,crawlers,crawlers.tjrj,crawlers.trf3,crawlers.tjmg,crawlers.trf4,crawlers.scrfb,crawlers.stj,crawlers.tst,crawlers.titsp,crawlers.carf,crawlers.tjsp,crawlers.tjrs,crawlers.tjba,downloader --concurrency=2 -E --loglevel=INFO'
    environment:
      - SENTRY_DSN=https://ca631cca1ff44e1d8c95e233b603eb0a@o926432.ingest.sentry.io/5880279
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/gcloud/service-account.json
      - CELERYD_HIJACK_ROOT_LOGGER=false
      - C_FORCE_ROOT='true'
      - TJSP_USERNAME
      - TJSP_PASSWORD
      - CLOUD_LOGGING_ENABLED
    volumes:
      - .:/opt/service
      - .service-account.json:/etc/gcloud/service-account.json

  beat:
    <<: *celery
    container_name: 'inspira-crawlers-beat'
    command: 'celery -A tasks beat -s .celerybeat-schedule'
    volumes:
      - .:/opt/service
      - .celerybeat-schedule:/opt/service/.celerybeat-schedule

  celery_tjsp:
    <<: *celery
    container_name: 'inspira-crawlers-tjsp'
    command: 'celery -A tasks worker -Q tjsp --concurrency=2 -E --loglevel=INFO -n worker.tjsp'

  celery_tjsp_pdf:
    <<: *celery
    container_name: 'inspira-crawlers-tjsp-pdf'
    command: 'celery -A tasks worker -Q tjsp.pdf --concurrency=5 -E --loglevel=INFO -n worker.tjsp-pdf'

  flower:
    build: .
    image: inspira-crawlers
    network_mode: 'service:redis'
    container_name: 'inspira-crawlers-flower'
    command: 'celery -A tasks flower --port=5555'
    environment:
      - CELERYD_HIJACK_ROOT_LOGGER=false
      - C_FORCE_ROOT='true'
    volumes:
      - .:/opt/service