[tool.poetry]
name = "inspira-crawlers"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
bs4 = "^0.0.1"
requests = "^2.25.1"
pendulum = "^2.1.2"
selenium = "^3.141.0"
google-cloud-storage = "^1.38.0"
click = ">=7.0,<8.0"
tqdm = "^4.61.1"
gql = {extras = ["aiohttp"], version = "^2.0.0"}
asyncio-throttle = "^1.0.2"
python-dotenv = "^0.17.1"
celery = {version = "^5.1.1", extras = ["redis"]}
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
