apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: crawlers
spec:
  selector:
    matchLabels:
      app: redis
      group: pipeline
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        group: pipeline
    spec:
      containers:
      - name: redis
        image: redis:7.0-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            cpu: "100m"
            memory: "2Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
