apiVersion: batch/v1
kind: Job
metadata:
  name: crawler-${K8S_JOB_NAME}
  namespace: crawlers
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: crawler
        image: us-docker.pkg.dev/inspira-registry/docker/data/crawlers:${IMAGE_TAG}
        imagePullPolicy: Always
        command: [ "bash", "-c" ]
        args: [ "python -m app.commands ${JOB_NAME} ${PARAMS}" ]
        envFrom:
        - secretRef:
            name: crawler-env
        volumeMounts:
        - mountPath: "/etc/gcloud"
          name: gcp-credentials
      volumes:
      - name: gcp-credentials
        secret:
          secretName: crawlers-credentials
      restartPolicy: Never


