apiVersion: batch/v1
kind: CronJob
metadata:
  name: trf3-crawler
  namespace: crawlers
spec:
  schedule: "10 3 */2 * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crawler
            image: us-docker.pkg.dev/inspira-registry/docker/data/crawlers:${IMAGE_TAG}
            imagePullPolicy: IfNotPresent
            command: [ "python", "commands.py", "trf3", "--output-uri", "gs://inspira-production-buckets-trf3" ]
            envFrom:
            - secretRef:
                name: crawler-env
            volumeMounts:
            - mountPath: "/etc/gcloud"
              name: gcp-credentials
          restartPolicy: Never
          volumes:
          - name: gcp-credentials
            secret:
              secretName: crawlers-credentials
