apiVersion: batch/v1
kind: CronJob
metadata:
  name: trf1-pdf-crawler
spec:
  schedule: "10 6 */2 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crawler
            image: us-docker.pkg.dev/inspira-registry/docker/data/crawlers:latest
            imagePullPolicy: Always
            command: [ "/bin/bash", "-c" ]
            args:
            - export PREFIX=$(TZ=UTC+167 date +"%Y/%m");
              python commands.py trf1-pdf --prefix "${PREFIX}" --local --input-uri gs://inspira-production-buckets-trf1
            envFrom:
            - secretRef:
                name: crawler-env
            volumeMounts:
            - mountPath: "/etc/gcloud"
              name: gcp-credentials
          restartPolicy: Never
          volumes:
          - name: gcp-credentials
            secret:
              secretName: crawlers-credentials
