apiVersion: batch/v1
kind: CronJob
metadata:
  name: tjdf-crawler
  namespace: crawlers
spec:
  schedule: "10 3 */2 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crawler
            image: us-docker.pkg.dev/inspira-registry/docker/data/crawlers:${IMAGE_TAG}
            imagePullPolicy: IfNotPresent
            command: [ "/bin/bash", "-c" ]
            args:
            - python commands.py tjdf --output-uri gs://inspira-production-buckets-tjdf
            envFrom:
            - secretRef:
                name: crawler-env
            volumeMounts:
            - mountPath: "/etc/gcloud"
              name: gcp-credentials
          restartPolicy: Never
          volumes:
          - name: gcp-credentials
            secret:
              secretName: crawlers-credentials
